version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-db
    platform: linux/amd64
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=secret
      - APP_USER=transporte_user
      - APP_USER_PASSWORD=transporte_pass
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 20
    networks:
      - transporte-network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - transporte-network

  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      # CAMBIO CLAVE: Usamos xepdb1 que es donde vive tu usuario
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/xepdb1
      - SPRING_DATASOURCE_USERNAME=transporte_user
      - SPRING_DATASOURCE_PASSWORD=transporte_pass
      # AÑADE ESTA LÍNEA:
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.OracleDialect
      # Opcional pero recomendado para ver qué está pasando:
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - AZURE_TENANT_NAME=EmpresaDuoc
      - AZURE_POLICY_NAME=B2C_1_B5_DUOC_FLOW
      - AZURE_CLIENT_ID=7f588d12-6261-4a95-b9ee-f2a0a329259a
    depends_on:
      rabbitmq:
        condition: service_healthy
      oracle-db:
        condition: service_healthy
    networks:
      - transporte-network
    volumes:
      - horarios-data:/app/data/horarios

networks:
  transporte-network:
    driver: bridge

volumes:
  horarios-data:
  oracle-data: